# Generated by Django 2.0.1 on 2019-11-22 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='活动ID')),
                ('title', models.CharField(max_length=100, verbose_name='活动标题')),
                ('description', models.TextField(default='emmm', verbose_name='活动描述')),
                ('prize', models.TextField(default='emmm', verbose_name='活动奖品')),
                ('start_time', models.CharField(max_length=20, verbose_name='起始时间')),
                ('end_time', models.CharField(max_length=20, verbose_name='结束时间')),
                ('posters', models.URLField(verbose_name='海报地址')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('host', models.CharField(max_length=50, verbose_name='主办方')),
                ('select_way', models.CharField(max_length=100, verbose_name='评选方式')),
                ('register_method', models.CharField(max_length=200, verbose_name='报名方式')),
                ('work_require', models.TextField(default='emmm', verbose_name='作品要求')),
            ],
            options={
                'verbose_name': '活动管理',
                'verbose_name_plural': '活动管理',
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cid', models.CharField(default='', max_length=150, verbose_name='影集id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('title', models.CharField(default='无题', max_length=50, null=True, verbose_name='标题')),
                ('description', models.CharField(default='', max_length=200, null=True, verbose_name='描述')),
                ('private', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('priview_photo', models.CharField(default='', max_length=200, null=True)),
                ('like_num', models.IntegerField(default=0, null=True)),
                ('comment_num', models.IntegerField(default=0, null=True)),
                ('share_num', models.IntegerField(default=0, null=True)),
                ('photos_num', models.IntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name': '影集管理',
                'verbose_name_plural': '影集管理',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(default='zzz', max_length=30, verbose_name='用户名')),
                ('userCall', models.CharField(default='zzz', max_length=20, verbose_name='称呼')),
                ('publishTime', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('textInfo', models.TextField(verbose_name='内容')),
                ('contactInfo', models.CharField(default='', max_length=30, verbose_name='联系方式')),
            ],
            options={
                'verbose_name': '联系管理',
                'verbose_name_plural': '联系管理',
                'ordering': ['-publishTime'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(default='zzz', max_length=30, verbose_name='用户名')),
                ('publishTime', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('textInfo', models.TextField(verbose_name='内容')),
                ('contactInfo', models.CharField(default='', max_length=30, verbose_name='联系方式')),
            ],
            options={
                'verbose_name': '意见反馈',
                'verbose_name_plural': '意见反馈',
                'ordering': ['-publishTime'],
            },
        ),
        migrations.CreateModel(
            name='Imgitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('iid', models.CharField(default='', max_length=150, verbose_name='图片id')),
                ('activity_id', models.IntegerField(default=-1, null=True, verbose_name='活动id')),
                ('categotire', models.CharField(default='other', max_length=20, null=True, verbose_name='分类')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('times_stamp', models.IntegerField(default=0)),
                ('title', models.CharField(default='无题', max_length=50, null=True, verbose_name='标题')),
                ('description', models.CharField(default='', max_length=200, null=True)),
                ('location', models.CharField(default='', max_length=50, null=True, verbose_name='拍摄地')),
                ('color', models.CharField(default='#d7d7d7', max_length=50, null=True)),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('isPassed', models.BooleanField(default=False, verbose_name='是否审核通过')),
                ('featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('isPrivate', models.BooleanField(default=False, verbose_name='是否私密')),
                ('like_num', models.IntegerField(default=0, null=True)),
                ('comment_num', models.IntegerField(default=0, null=True)),
                ('share_num', models.IntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name': '图片管理',
                'verbose_name_plural': '图片管理',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ImgUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.URLField(default='', max_length=100)),
                ('ragular', models.URLField(default='', max_length=100)),
                ('small', models.URLField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='交易ID')),
                ('is_done', models.BooleanField(default=False, verbose_name='是否解决')),
                ('start_time', models.CharField(max_length=100, verbose_name='起始时间')),
                ('end_time', models.CharField(max_length=100, verbose_name='结束时间')),
                ('require', models.TextField(verbose_name='具体要求')),
                ('thing', models.TextField(verbose_name='做什么事')),
                ('money', models.CharField(default='私聊或面谈', max_length=100, null=True, verbose_name='价格说明')),
                ('place', models.CharField(max_length=200, verbose_name='约拍地点')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '交易信息管理',
                'verbose_name_plural': '交易信息管理',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='消息id')),
                ('type', models.IntegerField(default=1, verbose_name='消息种类')),
                ('rule', models.CharField(default='like', max_length=10, verbose_name='消息作用类型')),
                ('target_id', models.CharField(default='all', max_length=200, null=True, verbose_name='目标id')),
                ('target_type', models.IntegerField(default=1, verbose_name='目标种类')),
                ('sender_id', models.IntegerField(null=True, verbose_name='发送者id')),
                ('sender_type', models.IntegerField(default=1, verbose_name='发送者种类')),
                ('content', models.TextField(default='', null=True, verbose_name='内容')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '消息管理',
                'verbose_name_plural': '消息管理',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Postcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='卡片名片ID')),
                ('is_passed', models.BooleanField(default=False, verbose_name='是否通过')),
                ('canvas_img_id', models.CharField(default='', max_length=150, verbose_name='卡片canvas云id')),
                ('by_name', models.CharField(max_length=50, verbose_name='寄卡人署名')),
                ('to_name', models.CharField(default='远方的ta', max_length=50, null=True, verbose_name='收卡人称呼')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('date', models.CharField(max_length=10, verbose_name='日期')),
                ('year', models.CharField(max_length=10, verbose_name='年份')),
            ],
            options={
                'verbose_name': '卡片管理',
                'verbose_name_plural': '卡片管理',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(default='', max_length=20)),
                ('urls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ImgUrls')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键')),
                ('pid', models.IntegerField(verbose_name='收留的卡片ID')),
                ('uid', models.CharField(default='', max_length=50, verbose_name='用户ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='收留时间')),
            ],
            options={
                'verbose_name': '用户收留卡片管理',
                'verbose_name_plural': '用户收留卡片管理',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscribeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50, verbose_name='用户id')),
                ('rule', models.CharField(default='like', max_length=10, verbose_name='消息作用类型')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
        ),
        migrations.CreateModel(
            name='SubscribeNotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50, verbose_name='用户id')),
                ('rule', models.CharField(default='like', max_length=10, verbose_name='消息作用类型')),
                ('target_id', models.CharField(default='all', max_length=100, null=True, verbose_name='目标id')),
                ('target_type', models.IntegerField(default=1, verbose_name='目标种类')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户消息订阅管理',
                'verbose_name_plural': '用户消息订阅管理',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20, null=True)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('uid', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='zzz', max_length=30, verbose_name='用户名')),
                ('location', models.CharField(default='广东省,广州市,天河区', max_length=30, null=True, verbose_name='地区')),
                ('gender', models.BooleanField(default=False, verbose_name='性别')),
                ('avater', models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUE2xfJCJDzzYAJbA_nHiDc95Dizm864c9Z6_6Lyp67D7YNpmONg', null=True)),
                ('cover_img', models.CharField(default='https://6c65-lengying-5889da-1258620266.tcb.qcloud.la/public/me.jpg?sign=f15b743f1b5ef570e643555f2262b91f&t=1557139702', max_length=200, null=True)),
                ('description', models.CharField(default='摄影师必须是照片的一部分。 ', max_length=400, null=True)),
                ('school', models.CharField(default='设置你的高校', max_length=50, null=True)),
                ('upload_accept', models.BooleanField(default=False)),
                ('login_accept', models.BooleanField(default=False)),
                ('total_likes', models.IntegerField(default=0, null=True)),
                ('total_collections', models.IntegerField(default=0, null=True)),
                ('total_photos', models.IntegerField(default=0, null=True)),
                ('followers_count', models.IntegerField(default=0, null=True)),
                ('following_count', models.IntegerField(default=0, null=True)),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('tags', models.ManyToManyField(null=True, to='api.Tags')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
                'ordering': ['-register_time'],
            },
        ),
        migrations.CreateModel(
            name='UserGeoinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('uid', models.CharField(default='', max_length=50)),
                ('lat', models.FloatField(verbose_name='纬度')),
                ('long', models.FloatField(verbose_name='经度')),
                ('geohash_value', models.CharField(max_length=20, verbose_name='哈希值')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户geo管理',
                'verbose_name_plural': '用户geo管理',
                'ordering': ['-update_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotifyQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('rule', models.CharField(default='like', max_length=10, verbose_name='消息作用类型')),
                ('notify_id', models.IntegerField(verbose_name='消息id')),
                ('uid', models.CharField(max_length=50, verbose_name='用户id')),
                ('is_read', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户消息队列管理',
                'verbose_name_plural': '用户消息队列管理',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Witget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_nums', models.IntegerField(default=0, null=True)),
                ('comment_nums', models.IntegerField(default=0, null=True)),
                ('share_nums', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='postcard',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='market',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='imgitem',
            name='tags',
            field=models.ManyToManyField(null=True, to='api.Tags'),
        ),
        migrations.AddField(
            model_name='imgitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='collections',
            name='tags',
            field=models.ManyToManyField(to='api.Tags'),
        ),
        migrations.AddField(
            model_name='collections',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
